libvpxdec: Fix "error: implicit declaration of function ‘av_check_image_size’".
av_check_image_size() is declared in libavcore/imgutils.h.

Originally committed as revision 24717 to svn://svn.ffmpeg.org/ffmpeg/trunk