error: remove symbols which were deprecated before the big bump
The removal was not applied when merging the Libav patches, because
there was still code referencing the symbols.

Signed-off-by: Stefano Sabatini <stefano.sabatini-lala@poste.it>