lavfi/asyncts: Fix compilation with GCC 4.7
Compilation failed since commit 42d621d131a45fb63571ca6029c2fc4f02811c10
Error messages:
libavfilter/af_asyncts.c:249:5: error: initializer element is not
computable at load time
libavfilter/af_asyncts.c:249:5: error: (near initialization for
‘avfilter_af_asyncts.priv_size’)

Signed-off-by: Michael Niedermayer <michaelni@gmx.at>